name: Primo Rubber Co
title: Primo Rubber Co
baseurl: "/blog"
url: "https://primorubberco.com"
theme: minima
logo: "/logo.png"
favicon: "/favicon-32x32.png"
# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

contact_note: >
  You can even add a little note about which of these is the best way to reach you.
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  Blog posts from Primo Rubber Co. Discussing rubber manufacturing and case studies.
footer_text: >
  <a href="/#contact" target="_blank">Contact Us</a>
keywords: rubber molding, custom rubber parts, rubber injection molding, rubber manufacturing, american based rubber manufacturing, # add your own keywords or leave empty
lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
